name = 'Kijani'
license = 'MIT'
licenselink = 'https://github.com/innoviter/kijani-hugo-theme/LICENSE'
description = 'Minimal dark Hugo theme based on Tailwind'

homepage = 'https://github.com/innoviter/kijani-hugo-theme'

demosite = 'https://owner.github.io/repo'

tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

[author]
  name = 'Mischa Zöller'
  homepage = 'https://innoviter.com'
